# Generated by Django 5.0.8 on 2024-08-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_precos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precos',
            name='preco',
            field=models.IntegerField(max_length=7, verbose_name='Preços'),
        ),
    ]
