# Generated by Django 5.0.8 on 2024-08-13 23:55

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_preco_delete_precos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testemunho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ocupacao', models.CharField(max_length=100, verbose_name='Ocupação')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='Clientes', variations={'thumb': {'crop': True, 'height': 400, 'width': 400}}, verbose_name='Imagem')),
                ('estrelas', models.CharField(choices=[('lni-star-filledlni-star-filledlni-star-filledlni-star-filledlni-star-filled', '5 estrelas'), ('lni-star-filledlni-star-filledlni-star-filledlni-star-filled', '4 estrelas'), ('lni-star-filledlni-star-filledlni-star-filled', '3 estrelas'), ('lni-star-filledlni-star-filled', '2 estrelas'), ('lni-star-filled', '1 estrelas')], max_length=100, verbose_name='Estrelas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
