# Generated by Django 5.0.8 on 2024-08-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_testemunho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testemunho',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='testemunho',
            name='criado',
        ),
        migrations.RemoveField(
            model_name='testemunho',
            name='modificado',
        ),
        migrations.AlterField(
            model_name='testemunho',
            name='estrelas',
            field=models.CharField(choices=[('<i class="lni lni-star-filled"></i><i class="lni lni-star-filled"></i><i class="lni lni-star-filled"></i><i class="lni lni-star-filled"></i><i class="lni lni-star-filled"></i>', '5 estrelas'), ('<i class="lni lni-star-filled"></i><i class="lni lni-star-filled"></i><i class="lni lni-star-filled"></i><i class="lni lni-star-filled"></i>', '4 estrelas'), ('<i class="lni lni-star-filled"></i><i class="lni lni-star-filled"></i><i class="lni lni-star-filled"></i>', '3 estrelas'), ('<i class="lni lni-star-filled"></i><i class="lni lni-star-filled"></i>', '2 estrelas'), ('<i class="lni lni-star-filled"></i>', '1 estrela')], max_length=200, verbose_name='Estrelas'),
        ),
    ]
