# Generated by Django 5.0.8 on 2024-08-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_testemunho_ativo_remove_testemunho_criado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testemunho',
            name='estrelas',
            field=models.CharField(choices=[('lni-star-filled, lni-star-filled, lni-star-filled, lni-star-filled, lni-star-filled', '5 estrelas'), ('lni-star-filled, lni-star-filled, lni-star-filled, lni-star-filled', '4 estrelas'), ('lni-star-filled, lni-star-filled', '3 estrelas'), ('lni-star-filled, lni-star-filled', '2 estrelas'), ('lni-star-filled', '1 estrela')], max_length=200, verbose_name='Estrelas'),
        ),
    ]
